# Generated by Django 6.1 on 2026-08-10 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_blog_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image_path',
            field=models.ImageField(upload_to='blogs/'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.SlugField(max_length=225, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=225, unique=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='path',
            field=models.ImageField(upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=225, unique=True),
        ),
        migrations.AddConstraint(
            model_name='image',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('product',), name='unique_default_image_per_product'),
        ),
    ]
